### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by ZeeRaider** [Seggan/Slimy-Power-Suits#10]
After updating all the Slimefun Addons to the latest and the main+CScore I get this error on load:

[20:23:17] [Server thread/ERROR]: Error occurred while enabling SlimyPowerSuits vDEV - 9 (git 6d6bb2e7) (Is it up to date?)
java.lang.NoSuchMethodError: 'void me.mrCookieSlime.Slimefun.Objects.Category.register()'
    at io.github.seggan.slimypowersuits.SlimyPowerSuits.onEnable(SlimyPowerSuits.java:47) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:240) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:933) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.4.jar:git-Tuinity-"8954b61"]
    at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Seggan** [comment]
Fixed
