### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by bobhenl** [Seggan/Slimy-Power-Suits#2]
Hi, I got this error in console
```
[00:07:34] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to SlimyPowerSuits vDEV - 4 (git 1374b7c3)
java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was -0.54923415184021. (attribute base value: 20.0, player: holo22)
	at org.bukkit.craftbukkit.v1_16_R2.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:117) ~[patched_1.16.3.jar:git-Paper-204]
	at io.github.seggan.slimypowersuits.handlers.PowerSuitHandler.onPlayerHurt(PowerSuitHandler.java:99) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor942.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-204]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:252) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:908) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:885) ~[patched_1.16.3.jar:git-Paper-204]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1074) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity0(EntityLiving.java:1825) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityHuman.damageEntity0(EntityHuman.java:844) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1160) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityHuman.damageEntity(EntityHuman.java:761) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityPlayer.damageEntity(EntityPlayer.java:838) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityFireworks.m(EntityFireworks.java:233) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityFireworks.explode(EntityFireworks.java:151) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.EntityFireworks.tick(EntityFireworks.java:142) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:841) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.World.a(World.java:884) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:526) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-204]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-204]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```
And nobody wears power suit.

**Comment by Seggan** [comment]
@Volgeop hey, you may ignore the error as it is harmless and will not break anything. However I will fix it in build 6.

**Comment by Seggan** [comment]
fixed. build 6
